# Generated by Django 3.0.6 on 2020-05-15 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import libs.helpers.datetimepresets


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonRegistrationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128, verbose_name='Email')),
                ('url', models.CharField(max_length=64, verbose_name='URL Prefix')),
                ('key', models.CharField(max_length=128, verbose_name='Registration key')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('expired_at', models.DateTimeField(default=libs.helpers.datetimepresets.day_later, verbose_name='Expired at')),
            ],
            options={
                'verbose_name': 'Person Registrations Request',
                'verbose_name_plural': 'Person Registrations Requests',
                'db_table': 'core_person_registration_request',
                'ordering': ['-expired_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=128, null=True, verbose_name='Phone number')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User of system')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Persons',
                'db_table': 'core_person',
                'ordering': ['-updated_at'],
            },
        ),
    ]
